#
# DispenseIt 0.3
# By Kieraan
#

# Console Logging.
# ALL = Outputs all dispenser usage and attempts at placing dispensers.
# BLOCKED = Outputs blocked dispenser usage and attempts at placing dispensers.
# NONE = Outputs nothing.

consoleLog: ALL

# Placement Permissions.
# true = Players need the dispenseit.place permission node to place dispensers/droppers.
# false = Player do not need any permission nodes to place dispensers/droppers.

usePermission: 
  dispenser: false
  dropper: false

# Item Blacklisting
# true = Blocks the item/block from being dispensed/dropped.
# false = Allows the item/block from being dispensed/dropped.
# Note: You may add any item to this list, please lookup the correct name, however.

blacklist:

  dispenser:    
    WATER_BUCKET: false
    LAVA_BUCKET: false
    ARROW: false
    FIREBALL: false
    EGG: false
    SNOW_BALL: false
    POTION: false
    EXP_BOTTLE: false
    MINECART: false
    STORAGE_MINECART: false
    POWERED_MINECART: false
    BOAT: false
    MONSTER_EGG: false
    
  dropper:
    WATER_BUCKET: false
    LAVA_BUCKET: false
    ARROW: false
    FIREBALL: false
    EGG: false
    SNOW_BALL: false
    POTION: false
    EXP_BOTTLE: false
    MINECART: false
    STORAGE_MINECART: false
    POWERED_MINECART: false
    BOAT: false
    MONSTER_EGG: false

# Also note: MONSTER_EGG accounts for all spawn eggs, non-hostile and hostile.

